
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const authProvider = {
  EMAIL: 'EMAIL',
  GOOGLE: 'GOOGLE'
} as const

export type authProvider = (typeof authProvider)[keyof typeof authProvider]


export const UserStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED'
} as const

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus]


export const EventType = {
  JOIN_BCN: 'JOIN_BCN',
  COURSE_COMPLETE: 'COURSE_COMPLETE',
  QUIZ_COMPLETE: 'QUIZ_COMPLETE',
  PROJECT_COMPLETE: 'PROJECT_COMPLETE',
  SEMESTER_COMPLETE: 'SEMESTER_COMPLETE'
} as const

export type EventType = (typeof EventType)[keyof typeof EventType]
