
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ReadReceipt` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ReadReceipt
 * 
 */
export type ReadReceiptModel = runtime.Types.Result.DefaultSelection<Prisma.$ReadReceiptPayload>

export type AggregateReadReceipt = {
  _count: ReadReceiptCountAggregateOutputType | null
  _min: ReadReceiptMinAggregateOutputType | null
  _max: ReadReceiptMaxAggregateOutputType | null
}

export type ReadReceiptMinAggregateOutputType = {
  id: string | null
  messageId: string | null
  userId: string | null
  readAt: Date | null
}

export type ReadReceiptMaxAggregateOutputType = {
  id: string | null
  messageId: string | null
  userId: string | null
  readAt: Date | null
}

export type ReadReceiptCountAggregateOutputType = {
  id: number
  messageId: number
  userId: number
  readAt: number
  _all: number
}


export type ReadReceiptMinAggregateInputType = {
  id?: true
  messageId?: true
  userId?: true
  readAt?: true
}

export type ReadReceiptMaxAggregateInputType = {
  id?: true
  messageId?: true
  userId?: true
  readAt?: true
}

export type ReadReceiptCountAggregateInputType = {
  id?: true
  messageId?: true
  userId?: true
  readAt?: true
  _all?: true
}

export type ReadReceiptAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReadReceipt to aggregate.
   */
  where?: Prisma.ReadReceiptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReadReceipts to fetch.
   */
  orderBy?: Prisma.ReadReceiptOrderByWithRelationInput | Prisma.ReadReceiptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReadReceiptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReadReceipts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReadReceipts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ReadReceipts
  **/
  _count?: true | ReadReceiptCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReadReceiptMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReadReceiptMaxAggregateInputType
}

export type GetReadReceiptAggregateType<T extends ReadReceiptAggregateArgs> = {
      [P in keyof T & keyof AggregateReadReceipt]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReadReceipt[P]>
    : Prisma.GetScalarType<T[P], AggregateReadReceipt[P]>
}




export type ReadReceiptGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReadReceiptWhereInput
  orderBy?: Prisma.ReadReceiptOrderByWithAggregationInput | Prisma.ReadReceiptOrderByWithAggregationInput[]
  by: Prisma.ReadReceiptScalarFieldEnum[] | Prisma.ReadReceiptScalarFieldEnum
  having?: Prisma.ReadReceiptScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReadReceiptCountAggregateInputType | true
  _min?: ReadReceiptMinAggregateInputType
  _max?: ReadReceiptMaxAggregateInputType
}

export type ReadReceiptGroupByOutputType = {
  id: string
  messageId: string
  userId: string
  readAt: Date
  _count: ReadReceiptCountAggregateOutputType | null
  _min: ReadReceiptMinAggregateOutputType | null
  _max: ReadReceiptMaxAggregateOutputType | null
}

type GetReadReceiptGroupByPayload<T extends ReadReceiptGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReadReceiptGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReadReceiptGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReadReceiptGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReadReceiptGroupByOutputType[P]>
      }
    >
  >



export type ReadReceiptWhereInput = {
  AND?: Prisma.ReadReceiptWhereInput | Prisma.ReadReceiptWhereInput[]
  OR?: Prisma.ReadReceiptWhereInput[]
  NOT?: Prisma.ReadReceiptWhereInput | Prisma.ReadReceiptWhereInput[]
  id?: Prisma.StringFilter<"ReadReceipt"> | string
  messageId?: Prisma.StringFilter<"ReadReceipt"> | string
  userId?: Prisma.StringFilter<"ReadReceipt"> | string
  readAt?: Prisma.DateTimeFilter<"ReadReceipt"> | Date | string
  Message?: Prisma.XOR<Prisma.MessageScalarRelationFilter, Prisma.MessageWhereInput>
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ReadReceiptOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  readAt?: Prisma.SortOrder
  Message?: Prisma.MessageOrderByWithRelationInput
  User?: Prisma.UserOrderByWithRelationInput
}

export type ReadReceiptWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  messageId_userId?: Prisma.ReadReceiptMessageIdUserIdCompoundUniqueInput
  AND?: Prisma.ReadReceiptWhereInput | Prisma.ReadReceiptWhereInput[]
  OR?: Prisma.ReadReceiptWhereInput[]
  NOT?: Prisma.ReadReceiptWhereInput | Prisma.ReadReceiptWhereInput[]
  messageId?: Prisma.StringFilter<"ReadReceipt"> | string
  userId?: Prisma.StringFilter<"ReadReceipt"> | string
  readAt?: Prisma.DateTimeFilter<"ReadReceipt"> | Date | string
  Message?: Prisma.XOR<Prisma.MessageScalarRelationFilter, Prisma.MessageWhereInput>
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "messageId_userId">

export type ReadReceiptOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  readAt?: Prisma.SortOrder
  _count?: Prisma.ReadReceiptCountOrderByAggregateInput
  _max?: Prisma.ReadReceiptMaxOrderByAggregateInput
  _min?: Prisma.ReadReceiptMinOrderByAggregateInput
}

export type ReadReceiptScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReadReceiptScalarWhereWithAggregatesInput | Prisma.ReadReceiptScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReadReceiptScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReadReceiptScalarWhereWithAggregatesInput | Prisma.ReadReceiptScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ReadReceipt"> | string
  messageId?: Prisma.StringWithAggregatesFilter<"ReadReceipt"> | string
  userId?: Prisma.StringWithAggregatesFilter<"ReadReceipt"> | string
  readAt?: Prisma.DateTimeWithAggregatesFilter<"ReadReceipt"> | Date | string
}

export type ReadReceiptCreateInput = {
  id: string
  readAt?: Date | string
  Message: Prisma.MessageCreateNestedOneWithoutReadReceiptInput
  User: Prisma.UserCreateNestedOneWithoutReadReceiptInput
}

export type ReadReceiptUncheckedCreateInput = {
  id: string
  messageId: string
  userId: string
  readAt?: Date | string
}

export type ReadReceiptUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Message?: Prisma.MessageUpdateOneRequiredWithoutReadReceiptNestedInput
  User?: Prisma.UserUpdateOneRequiredWithoutReadReceiptNestedInput
}

export type ReadReceiptUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  readAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReadReceiptCreateManyInput = {
  id: string
  messageId: string
  userId: string
  readAt?: Date | string
}

export type ReadReceiptUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReadReceiptUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  readAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReadReceiptListRelationFilter = {
  every?: Prisma.ReadReceiptWhereInput
  some?: Prisma.ReadReceiptWhereInput
  none?: Prisma.ReadReceiptWhereInput
}

export type ReadReceiptOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ReadReceiptMessageIdUserIdCompoundUniqueInput = {
  messageId: string
  userId: string
}

export type ReadReceiptCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  readAt?: Prisma.SortOrder
}

export type ReadReceiptMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  readAt?: Prisma.SortOrder
}

export type ReadReceiptMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  readAt?: Prisma.SortOrder
}

export type ReadReceiptCreateNestedManyWithoutMessageInput = {
  create?: Prisma.XOR<Prisma.ReadReceiptCreateWithoutMessageInput, Prisma.ReadReceiptUncheckedCreateWithoutMessageInput> | Prisma.ReadReceiptCreateWithoutMessageInput[] | Prisma.ReadReceiptUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.ReadReceiptCreateOrConnectWithoutMessageInput | Prisma.ReadReceiptCreateOrConnectWithoutMessageInput[]
  createMany?: Prisma.ReadReceiptCreateManyMessageInputEnvelope
  connect?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
}

export type ReadReceiptUncheckedCreateNestedManyWithoutMessageInput = {
  create?: Prisma.XOR<Prisma.ReadReceiptCreateWithoutMessageInput, Prisma.ReadReceiptUncheckedCreateWithoutMessageInput> | Prisma.ReadReceiptCreateWithoutMessageInput[] | Prisma.ReadReceiptUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.ReadReceiptCreateOrConnectWithoutMessageInput | Prisma.ReadReceiptCreateOrConnectWithoutMessageInput[]
  createMany?: Prisma.ReadReceiptCreateManyMessageInputEnvelope
  connect?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
}

export type ReadReceiptUpdateManyWithoutMessageNestedInput = {
  create?: Prisma.XOR<Prisma.ReadReceiptCreateWithoutMessageInput, Prisma.ReadReceiptUncheckedCreateWithoutMessageInput> | Prisma.ReadReceiptCreateWithoutMessageInput[] | Prisma.ReadReceiptUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.ReadReceiptCreateOrConnectWithoutMessageInput | Prisma.ReadReceiptCreateOrConnectWithoutMessageInput[]
  upsert?: Prisma.ReadReceiptUpsertWithWhereUniqueWithoutMessageInput | Prisma.ReadReceiptUpsertWithWhereUniqueWithoutMessageInput[]
  createMany?: Prisma.ReadReceiptCreateManyMessageInputEnvelope
  set?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  disconnect?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  delete?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  connect?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  update?: Prisma.ReadReceiptUpdateWithWhereUniqueWithoutMessageInput | Prisma.ReadReceiptUpdateWithWhereUniqueWithoutMessageInput[]
  updateMany?: Prisma.ReadReceiptUpdateManyWithWhereWithoutMessageInput | Prisma.ReadReceiptUpdateManyWithWhereWithoutMessageInput[]
  deleteMany?: Prisma.ReadReceiptScalarWhereInput | Prisma.ReadReceiptScalarWhereInput[]
}

export type ReadReceiptUncheckedUpdateManyWithoutMessageNestedInput = {
  create?: Prisma.XOR<Prisma.ReadReceiptCreateWithoutMessageInput, Prisma.ReadReceiptUncheckedCreateWithoutMessageInput> | Prisma.ReadReceiptCreateWithoutMessageInput[] | Prisma.ReadReceiptUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.ReadReceiptCreateOrConnectWithoutMessageInput | Prisma.ReadReceiptCreateOrConnectWithoutMessageInput[]
  upsert?: Prisma.ReadReceiptUpsertWithWhereUniqueWithoutMessageInput | Prisma.ReadReceiptUpsertWithWhereUniqueWithoutMessageInput[]
  createMany?: Prisma.ReadReceiptCreateManyMessageInputEnvelope
  set?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  disconnect?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  delete?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  connect?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  update?: Prisma.ReadReceiptUpdateWithWhereUniqueWithoutMessageInput | Prisma.ReadReceiptUpdateWithWhereUniqueWithoutMessageInput[]
  updateMany?: Prisma.ReadReceiptUpdateManyWithWhereWithoutMessageInput | Prisma.ReadReceiptUpdateManyWithWhereWithoutMessageInput[]
  deleteMany?: Prisma.ReadReceiptScalarWhereInput | Prisma.ReadReceiptScalarWhereInput[]
}

export type ReadReceiptCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ReadReceiptCreateWithoutUserInput, Prisma.ReadReceiptUncheckedCreateWithoutUserInput> | Prisma.ReadReceiptCreateWithoutUserInput[] | Prisma.ReadReceiptUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReadReceiptCreateOrConnectWithoutUserInput | Prisma.ReadReceiptCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ReadReceiptCreateManyUserInputEnvelope
  connect?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
}

export type ReadReceiptUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ReadReceiptCreateWithoutUserInput, Prisma.ReadReceiptUncheckedCreateWithoutUserInput> | Prisma.ReadReceiptCreateWithoutUserInput[] | Prisma.ReadReceiptUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReadReceiptCreateOrConnectWithoutUserInput | Prisma.ReadReceiptCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ReadReceiptCreateManyUserInputEnvelope
  connect?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
}

export type ReadReceiptUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ReadReceiptCreateWithoutUserInput, Prisma.ReadReceiptUncheckedCreateWithoutUserInput> | Prisma.ReadReceiptCreateWithoutUserInput[] | Prisma.ReadReceiptUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReadReceiptCreateOrConnectWithoutUserInput | Prisma.ReadReceiptCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ReadReceiptUpsertWithWhereUniqueWithoutUserInput | Prisma.ReadReceiptUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ReadReceiptCreateManyUserInputEnvelope
  set?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  disconnect?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  delete?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  connect?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  update?: Prisma.ReadReceiptUpdateWithWhereUniqueWithoutUserInput | Prisma.ReadReceiptUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ReadReceiptUpdateManyWithWhereWithoutUserInput | Prisma.ReadReceiptUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ReadReceiptScalarWhereInput | Prisma.ReadReceiptScalarWhereInput[]
}

export type ReadReceiptUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ReadReceiptCreateWithoutUserInput, Prisma.ReadReceiptUncheckedCreateWithoutUserInput> | Prisma.ReadReceiptCreateWithoutUserInput[] | Prisma.ReadReceiptUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReadReceiptCreateOrConnectWithoutUserInput | Prisma.ReadReceiptCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ReadReceiptUpsertWithWhereUniqueWithoutUserInput | Prisma.ReadReceiptUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ReadReceiptCreateManyUserInputEnvelope
  set?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  disconnect?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  delete?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  connect?: Prisma.ReadReceiptWhereUniqueInput | Prisma.ReadReceiptWhereUniqueInput[]
  update?: Prisma.ReadReceiptUpdateWithWhereUniqueWithoutUserInput | Prisma.ReadReceiptUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ReadReceiptUpdateManyWithWhereWithoutUserInput | Prisma.ReadReceiptUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ReadReceiptScalarWhereInput | Prisma.ReadReceiptScalarWhereInput[]
}

export type ReadReceiptCreateWithoutMessageInput = {
  id: string
  readAt?: Date | string
  User: Prisma.UserCreateNestedOneWithoutReadReceiptInput
}

export type ReadReceiptUncheckedCreateWithoutMessageInput = {
  id: string
  userId: string
  readAt?: Date | string
}

export type ReadReceiptCreateOrConnectWithoutMessageInput = {
  where: Prisma.ReadReceiptWhereUniqueInput
  create: Prisma.XOR<Prisma.ReadReceiptCreateWithoutMessageInput, Prisma.ReadReceiptUncheckedCreateWithoutMessageInput>
}

export type ReadReceiptCreateManyMessageInputEnvelope = {
  data: Prisma.ReadReceiptCreateManyMessageInput | Prisma.ReadReceiptCreateManyMessageInput[]
  skipDuplicates?: boolean
}

export type ReadReceiptUpsertWithWhereUniqueWithoutMessageInput = {
  where: Prisma.ReadReceiptWhereUniqueInput
  update: Prisma.XOR<Prisma.ReadReceiptUpdateWithoutMessageInput, Prisma.ReadReceiptUncheckedUpdateWithoutMessageInput>
  create: Prisma.XOR<Prisma.ReadReceiptCreateWithoutMessageInput, Prisma.ReadReceiptUncheckedCreateWithoutMessageInput>
}

export type ReadReceiptUpdateWithWhereUniqueWithoutMessageInput = {
  where: Prisma.ReadReceiptWhereUniqueInput
  data: Prisma.XOR<Prisma.ReadReceiptUpdateWithoutMessageInput, Prisma.ReadReceiptUncheckedUpdateWithoutMessageInput>
}

export type ReadReceiptUpdateManyWithWhereWithoutMessageInput = {
  where: Prisma.ReadReceiptScalarWhereInput
  data: Prisma.XOR<Prisma.ReadReceiptUpdateManyMutationInput, Prisma.ReadReceiptUncheckedUpdateManyWithoutMessageInput>
}

export type ReadReceiptScalarWhereInput = {
  AND?: Prisma.ReadReceiptScalarWhereInput | Prisma.ReadReceiptScalarWhereInput[]
  OR?: Prisma.ReadReceiptScalarWhereInput[]
  NOT?: Prisma.ReadReceiptScalarWhereInput | Prisma.ReadReceiptScalarWhereInput[]
  id?: Prisma.StringFilter<"ReadReceipt"> | string
  messageId?: Prisma.StringFilter<"ReadReceipt"> | string
  userId?: Prisma.StringFilter<"ReadReceipt"> | string
  readAt?: Prisma.DateTimeFilter<"ReadReceipt"> | Date | string
}

export type ReadReceiptCreateWithoutUserInput = {
  id: string
  readAt?: Date | string
  Message: Prisma.MessageCreateNestedOneWithoutReadReceiptInput
}

export type ReadReceiptUncheckedCreateWithoutUserInput = {
  id: string
  messageId: string
  readAt?: Date | string
}

export type ReadReceiptCreateOrConnectWithoutUserInput = {
  where: Prisma.ReadReceiptWhereUniqueInput
  create: Prisma.XOR<Prisma.ReadReceiptCreateWithoutUserInput, Prisma.ReadReceiptUncheckedCreateWithoutUserInput>
}

export type ReadReceiptCreateManyUserInputEnvelope = {
  data: Prisma.ReadReceiptCreateManyUserInput | Prisma.ReadReceiptCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ReadReceiptUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ReadReceiptWhereUniqueInput
  update: Prisma.XOR<Prisma.ReadReceiptUpdateWithoutUserInput, Prisma.ReadReceiptUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ReadReceiptCreateWithoutUserInput, Prisma.ReadReceiptUncheckedCreateWithoutUserInput>
}

export type ReadReceiptUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ReadReceiptWhereUniqueInput
  data: Prisma.XOR<Prisma.ReadReceiptUpdateWithoutUserInput, Prisma.ReadReceiptUncheckedUpdateWithoutUserInput>
}

export type ReadReceiptUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ReadReceiptScalarWhereInput
  data: Prisma.XOR<Prisma.ReadReceiptUpdateManyMutationInput, Prisma.ReadReceiptUncheckedUpdateManyWithoutUserInput>
}

export type ReadReceiptCreateManyMessageInput = {
  id: string
  userId: string
  readAt?: Date | string
}

export type ReadReceiptUpdateWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  User?: Prisma.UserUpdateOneRequiredWithoutReadReceiptNestedInput
}

export type ReadReceiptUncheckedUpdateWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  readAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReadReceiptUncheckedUpdateManyWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  readAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReadReceiptCreateManyUserInput = {
  id: string
  messageId: string
  readAt?: Date | string
}

export type ReadReceiptUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Message?: Prisma.MessageUpdateOneRequiredWithoutReadReceiptNestedInput
}

export type ReadReceiptUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  readAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReadReceiptUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  readAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ReadReceiptSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  messageId?: boolean
  userId?: boolean
  readAt?: boolean
  Message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["readReceipt"]>

export type ReadReceiptSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  messageId?: boolean
  userId?: boolean
  readAt?: boolean
  Message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["readReceipt"]>

export type ReadReceiptSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  messageId?: boolean
  userId?: boolean
  readAt?: boolean
  Message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["readReceipt"]>

export type ReadReceiptSelectScalar = {
  id?: boolean
  messageId?: boolean
  userId?: boolean
  readAt?: boolean
}

export type ReadReceiptOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "messageId" | "userId" | "readAt", ExtArgs["result"]["readReceipt"]>
export type ReadReceiptInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ReadReceiptIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ReadReceiptIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ReadReceiptPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ReadReceipt"
  objects: {
    Message: Prisma.$MessagePayload<ExtArgs>
    User: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    messageId: string
    userId: string
    readAt: Date
  }, ExtArgs["result"]["readReceipt"]>
  composites: {}
}

export type ReadReceiptGetPayload<S extends boolean | null | undefined | ReadReceiptDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReadReceiptPayload, S>

export type ReadReceiptCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReadReceiptFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: ReadReceiptCountAggregateInputType | true
  }

export interface ReadReceiptDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ReadReceipt'], meta: { name: 'ReadReceipt' } }
  /**
   * Find zero or one ReadReceipt that matches the filter.
   * @param {ReadReceiptFindUniqueArgs} args - Arguments to find a ReadReceipt
   * @example
   * // Get one ReadReceipt
   * const readReceipt = await prisma.readReceipt.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReadReceiptFindUniqueArgs>(args: Prisma.SelectSubset<T, ReadReceiptFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReadReceiptClient<runtime.Types.Result.GetResult<Prisma.$ReadReceiptPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ReadReceipt that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReadReceiptFindUniqueOrThrowArgs} args - Arguments to find a ReadReceipt
   * @example
   * // Get one ReadReceipt
   * const readReceipt = await prisma.readReceipt.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReadReceiptFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReadReceiptFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReadReceiptClient<runtime.Types.Result.GetResult<Prisma.$ReadReceiptPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReadReceipt that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReadReceiptFindFirstArgs} args - Arguments to find a ReadReceipt
   * @example
   * // Get one ReadReceipt
   * const readReceipt = await prisma.readReceipt.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReadReceiptFindFirstArgs>(args?: Prisma.SelectSubset<T, ReadReceiptFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReadReceiptClient<runtime.Types.Result.GetResult<Prisma.$ReadReceiptPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReadReceipt that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReadReceiptFindFirstOrThrowArgs} args - Arguments to find a ReadReceipt
   * @example
   * // Get one ReadReceipt
   * const readReceipt = await prisma.readReceipt.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReadReceiptFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReadReceiptFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReadReceiptClient<runtime.Types.Result.GetResult<Prisma.$ReadReceiptPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ReadReceipts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReadReceiptFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ReadReceipts
   * const readReceipts = await prisma.readReceipt.findMany()
   * 
   * // Get first 10 ReadReceipts
   * const readReceipts = await prisma.readReceipt.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const readReceiptWithIdOnly = await prisma.readReceipt.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReadReceiptFindManyArgs>(args?: Prisma.SelectSubset<T, ReadReceiptFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReadReceiptPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ReadReceipt.
   * @param {ReadReceiptCreateArgs} args - Arguments to create a ReadReceipt.
   * @example
   * // Create one ReadReceipt
   * const ReadReceipt = await prisma.readReceipt.create({
   *   data: {
   *     // ... data to create a ReadReceipt
   *   }
   * })
   * 
   */
  create<T extends ReadReceiptCreateArgs>(args: Prisma.SelectSubset<T, ReadReceiptCreateArgs<ExtArgs>>): Prisma.Prisma__ReadReceiptClient<runtime.Types.Result.GetResult<Prisma.$ReadReceiptPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ReadReceipts.
   * @param {ReadReceiptCreateManyArgs} args - Arguments to create many ReadReceipts.
   * @example
   * // Create many ReadReceipts
   * const readReceipt = await prisma.readReceipt.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReadReceiptCreateManyArgs>(args?: Prisma.SelectSubset<T, ReadReceiptCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ReadReceipts and returns the data saved in the database.
   * @param {ReadReceiptCreateManyAndReturnArgs} args - Arguments to create many ReadReceipts.
   * @example
   * // Create many ReadReceipts
   * const readReceipt = await prisma.readReceipt.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ReadReceipts and only return the `id`
   * const readReceiptWithIdOnly = await prisma.readReceipt.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ReadReceiptCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ReadReceiptCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReadReceiptPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ReadReceipt.
   * @param {ReadReceiptDeleteArgs} args - Arguments to delete one ReadReceipt.
   * @example
   * // Delete one ReadReceipt
   * const ReadReceipt = await prisma.readReceipt.delete({
   *   where: {
   *     // ... filter to delete one ReadReceipt
   *   }
   * })
   * 
   */
  delete<T extends ReadReceiptDeleteArgs>(args: Prisma.SelectSubset<T, ReadReceiptDeleteArgs<ExtArgs>>): Prisma.Prisma__ReadReceiptClient<runtime.Types.Result.GetResult<Prisma.$ReadReceiptPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ReadReceipt.
   * @param {ReadReceiptUpdateArgs} args - Arguments to update one ReadReceipt.
   * @example
   * // Update one ReadReceipt
   * const readReceipt = await prisma.readReceipt.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReadReceiptUpdateArgs>(args: Prisma.SelectSubset<T, ReadReceiptUpdateArgs<ExtArgs>>): Prisma.Prisma__ReadReceiptClient<runtime.Types.Result.GetResult<Prisma.$ReadReceiptPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ReadReceipts.
   * @param {ReadReceiptDeleteManyArgs} args - Arguments to filter ReadReceipts to delete.
   * @example
   * // Delete a few ReadReceipts
   * const { count } = await prisma.readReceipt.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReadReceiptDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReadReceiptDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReadReceipts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReadReceiptUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ReadReceipts
   * const readReceipt = await prisma.readReceipt.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReadReceiptUpdateManyArgs>(args: Prisma.SelectSubset<T, ReadReceiptUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReadReceipts and returns the data updated in the database.
   * @param {ReadReceiptUpdateManyAndReturnArgs} args - Arguments to update many ReadReceipts.
   * @example
   * // Update many ReadReceipts
   * const readReceipt = await prisma.readReceipt.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ReadReceipts and only return the `id`
   * const readReceiptWithIdOnly = await prisma.readReceipt.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ReadReceiptUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ReadReceiptUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReadReceiptPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ReadReceipt.
   * @param {ReadReceiptUpsertArgs} args - Arguments to update or create a ReadReceipt.
   * @example
   * // Update or create a ReadReceipt
   * const readReceipt = await prisma.readReceipt.upsert({
   *   create: {
   *     // ... data to create a ReadReceipt
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ReadReceipt we want to update
   *   }
   * })
   */
  upsert<T extends ReadReceiptUpsertArgs>(args: Prisma.SelectSubset<T, ReadReceiptUpsertArgs<ExtArgs>>): Prisma.Prisma__ReadReceiptClient<runtime.Types.Result.GetResult<Prisma.$ReadReceiptPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ReadReceipts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReadReceiptCountArgs} args - Arguments to filter ReadReceipts to count.
   * @example
   * // Count the number of ReadReceipts
   * const count = await prisma.readReceipt.count({
   *   where: {
   *     // ... the filter for the ReadReceipts we want to count
   *   }
   * })
  **/
  count<T extends ReadReceiptCountArgs>(
    args?: Prisma.Subset<T, ReadReceiptCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReadReceiptCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ReadReceipt.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReadReceiptAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReadReceiptAggregateArgs>(args: Prisma.Subset<T, ReadReceiptAggregateArgs>): Prisma.PrismaPromise<GetReadReceiptAggregateType<T>>

  /**
   * Group by ReadReceipt.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReadReceiptGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReadReceiptGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReadReceiptGroupByArgs['orderBy'] }
      : { orderBy?: ReadReceiptGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReadReceiptGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReadReceiptGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ReadReceipt model
 */
readonly fields: ReadReceiptFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ReadReceipt.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReadReceiptClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Message<T extends Prisma.MessageDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MessageDefaultArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  User<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ReadReceipt model
 */
export interface ReadReceiptFieldRefs {
  readonly id: Prisma.FieldRef<"ReadReceipt", 'String'>
  readonly messageId: Prisma.FieldRef<"ReadReceipt", 'String'>
  readonly userId: Prisma.FieldRef<"ReadReceipt", 'String'>
  readonly readAt: Prisma.FieldRef<"ReadReceipt", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ReadReceipt findUnique
 */
export type ReadReceiptFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadReceipt
   */
  select?: Prisma.ReadReceiptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadReceipt
   */
  omit?: Prisma.ReadReceiptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReadReceiptInclude<ExtArgs> | null
  /**
   * Filter, which ReadReceipt to fetch.
   */
  where: Prisma.ReadReceiptWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ReadReceipt findUniqueOrThrow
 */
export type ReadReceiptFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadReceipt
   */
  select?: Prisma.ReadReceiptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadReceipt
   */
  omit?: Prisma.ReadReceiptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReadReceiptInclude<ExtArgs> | null
  /**
   * Filter, which ReadReceipt to fetch.
   */
  where: Prisma.ReadReceiptWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ReadReceipt findFirst
 */
export type ReadReceiptFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadReceipt
   */
  select?: Prisma.ReadReceiptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadReceipt
   */
  omit?: Prisma.ReadReceiptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReadReceiptInclude<ExtArgs> | null
  /**
   * Filter, which ReadReceipt to fetch.
   */
  where?: Prisma.ReadReceiptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReadReceipts to fetch.
   */
  orderBy?: Prisma.ReadReceiptOrderByWithRelationInput | Prisma.ReadReceiptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReadReceipts.
   */
  cursor?: Prisma.ReadReceiptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReadReceipts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReadReceipts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReadReceipts.
   */
  distinct?: Prisma.ReadReceiptScalarFieldEnum | Prisma.ReadReceiptScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ReadReceipt findFirstOrThrow
 */
export type ReadReceiptFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadReceipt
   */
  select?: Prisma.ReadReceiptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadReceipt
   */
  omit?: Prisma.ReadReceiptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReadReceiptInclude<ExtArgs> | null
  /**
   * Filter, which ReadReceipt to fetch.
   */
  where?: Prisma.ReadReceiptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReadReceipts to fetch.
   */
  orderBy?: Prisma.ReadReceiptOrderByWithRelationInput | Prisma.ReadReceiptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReadReceipts.
   */
  cursor?: Prisma.ReadReceiptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReadReceipts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReadReceipts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReadReceipts.
   */
  distinct?: Prisma.ReadReceiptScalarFieldEnum | Prisma.ReadReceiptScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ReadReceipt findMany
 */
export type ReadReceiptFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadReceipt
   */
  select?: Prisma.ReadReceiptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadReceipt
   */
  omit?: Prisma.ReadReceiptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReadReceiptInclude<ExtArgs> | null
  /**
   * Filter, which ReadReceipts to fetch.
   */
  where?: Prisma.ReadReceiptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReadReceipts to fetch.
   */
  orderBy?: Prisma.ReadReceiptOrderByWithRelationInput | Prisma.ReadReceiptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ReadReceipts.
   */
  cursor?: Prisma.ReadReceiptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReadReceipts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReadReceipts.
   */
  skip?: number
  distinct?: Prisma.ReadReceiptScalarFieldEnum | Prisma.ReadReceiptScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ReadReceipt create
 */
export type ReadReceiptCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadReceipt
   */
  select?: Prisma.ReadReceiptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadReceipt
   */
  omit?: Prisma.ReadReceiptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReadReceiptInclude<ExtArgs> | null
  /**
   * The data needed to create a ReadReceipt.
   */
  data: Prisma.XOR<Prisma.ReadReceiptCreateInput, Prisma.ReadReceiptUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ReadReceipt createMany
 */
export type ReadReceiptCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ReadReceipts.
   */
  data: Prisma.ReadReceiptCreateManyInput | Prisma.ReadReceiptCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ReadReceipt createManyAndReturn
 */
export type ReadReceiptCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadReceipt
   */
  select?: Prisma.ReadReceiptSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReadReceipt
   */
  omit?: Prisma.ReadReceiptOmit<ExtArgs> | null
  /**
   * The data used to create many ReadReceipts.
   */
  data: Prisma.ReadReceiptCreateManyInput | Prisma.ReadReceiptCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReadReceiptIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ReadReceipt update
 */
export type ReadReceiptUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadReceipt
   */
  select?: Prisma.ReadReceiptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadReceipt
   */
  omit?: Prisma.ReadReceiptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReadReceiptInclude<ExtArgs> | null
  /**
   * The data needed to update a ReadReceipt.
   */
  data: Prisma.XOR<Prisma.ReadReceiptUpdateInput, Prisma.ReadReceiptUncheckedUpdateInput>
  /**
   * Choose, which ReadReceipt to update.
   */
  where: Prisma.ReadReceiptWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ReadReceipt updateMany
 */
export type ReadReceiptUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ReadReceipts.
   */
  data: Prisma.XOR<Prisma.ReadReceiptUpdateManyMutationInput, Prisma.ReadReceiptUncheckedUpdateManyInput>
  /**
   * Filter which ReadReceipts to update
   */
  where?: Prisma.ReadReceiptWhereInput
  /**
   * Limit how many ReadReceipts to update.
   */
  limit?: number
}

/**
 * ReadReceipt updateManyAndReturn
 */
export type ReadReceiptUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadReceipt
   */
  select?: Prisma.ReadReceiptSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReadReceipt
   */
  omit?: Prisma.ReadReceiptOmit<ExtArgs> | null
  /**
   * The data used to update ReadReceipts.
   */
  data: Prisma.XOR<Prisma.ReadReceiptUpdateManyMutationInput, Prisma.ReadReceiptUncheckedUpdateManyInput>
  /**
   * Filter which ReadReceipts to update
   */
  where?: Prisma.ReadReceiptWhereInput
  /**
   * Limit how many ReadReceipts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReadReceiptIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ReadReceipt upsert
 */
export type ReadReceiptUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadReceipt
   */
  select?: Prisma.ReadReceiptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadReceipt
   */
  omit?: Prisma.ReadReceiptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReadReceiptInclude<ExtArgs> | null
  /**
   * The filter to search for the ReadReceipt to update in case it exists.
   */
  where: Prisma.ReadReceiptWhereUniqueInput
  /**
   * In case the ReadReceipt found by the `where` argument doesn't exist, create a new ReadReceipt with this data.
   */
  create: Prisma.XOR<Prisma.ReadReceiptCreateInput, Prisma.ReadReceiptUncheckedCreateInput>
  /**
   * In case the ReadReceipt was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReadReceiptUpdateInput, Prisma.ReadReceiptUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ReadReceipt delete
 */
export type ReadReceiptDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadReceipt
   */
  select?: Prisma.ReadReceiptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadReceipt
   */
  omit?: Prisma.ReadReceiptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReadReceiptInclude<ExtArgs> | null
  /**
   * Filter which ReadReceipt to delete.
   */
  where: Prisma.ReadReceiptWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ReadReceipt deleteMany
 */
export type ReadReceiptDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReadReceipts to delete
   */
  where?: Prisma.ReadReceiptWhereInput
  /**
   * Limit how many ReadReceipts to delete.
   */
  limit?: number
}

/**
 * ReadReceipt without action
 */
export type ReadReceiptDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadReceipt
   */
  select?: Prisma.ReadReceiptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadReceipt
   */
  omit?: Prisma.ReadReceiptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReadReceiptInclude<ExtArgs> | null
}
