
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TokenBlacklist` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TokenBlacklist
 * 
 */
export type TokenBlacklistModel = runtime.Types.Result.DefaultSelection<Prisma.$TokenBlacklistPayload>

export type AggregateTokenBlacklist = {
  _count: TokenBlacklistCountAggregateOutputType | null
  _avg: TokenBlacklistAvgAggregateOutputType | null
  _sum: TokenBlacklistSumAggregateOutputType | null
  _min: TokenBlacklistMinAggregateOutputType | null
  _max: TokenBlacklistMaxAggregateOutputType | null
}

export type TokenBlacklistAvgAggregateOutputType = {
  id: number | null
}

export type TokenBlacklistSumAggregateOutputType = {
  id: number | null
}

export type TokenBlacklistMinAggregateOutputType = {
  id: number | null
  token: string | null
  createdAt: Date | null
  expiresAt: Date | null
}

export type TokenBlacklistMaxAggregateOutputType = {
  id: number | null
  token: string | null
  createdAt: Date | null
  expiresAt: Date | null
}

export type TokenBlacklistCountAggregateOutputType = {
  id: number
  token: number
  createdAt: number
  expiresAt: number
  _all: number
}


export type TokenBlacklistAvgAggregateInputType = {
  id?: true
}

export type TokenBlacklistSumAggregateInputType = {
  id?: true
}

export type TokenBlacklistMinAggregateInputType = {
  id?: true
  token?: true
  createdAt?: true
  expiresAt?: true
}

export type TokenBlacklistMaxAggregateInputType = {
  id?: true
  token?: true
  createdAt?: true
  expiresAt?: true
}

export type TokenBlacklistCountAggregateInputType = {
  id?: true
  token?: true
  createdAt?: true
  expiresAt?: true
  _all?: true
}

export type TokenBlacklistAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TokenBlacklist to aggregate.
   */
  where?: Prisma.TokenBlacklistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TokenBlacklists to fetch.
   */
  orderBy?: Prisma.TokenBlacklistOrderByWithRelationInput | Prisma.TokenBlacklistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TokenBlacklistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TokenBlacklists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TokenBlacklists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TokenBlacklists
  **/
  _count?: true | TokenBlacklistCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TokenBlacklistAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TokenBlacklistSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TokenBlacklistMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TokenBlacklistMaxAggregateInputType
}

export type GetTokenBlacklistAggregateType<T extends TokenBlacklistAggregateArgs> = {
      [P in keyof T & keyof AggregateTokenBlacklist]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTokenBlacklist[P]>
    : Prisma.GetScalarType<T[P], AggregateTokenBlacklist[P]>
}




export type TokenBlacklistGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TokenBlacklistWhereInput
  orderBy?: Prisma.TokenBlacklistOrderByWithAggregationInput | Prisma.TokenBlacklistOrderByWithAggregationInput[]
  by: Prisma.TokenBlacklistScalarFieldEnum[] | Prisma.TokenBlacklistScalarFieldEnum
  having?: Prisma.TokenBlacklistScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TokenBlacklistCountAggregateInputType | true
  _avg?: TokenBlacklistAvgAggregateInputType
  _sum?: TokenBlacklistSumAggregateInputType
  _min?: TokenBlacklistMinAggregateInputType
  _max?: TokenBlacklistMaxAggregateInputType
}

export type TokenBlacklistGroupByOutputType = {
  id: number
  token: string
  createdAt: Date
  expiresAt: Date
  _count: TokenBlacklistCountAggregateOutputType | null
  _avg: TokenBlacklistAvgAggregateOutputType | null
  _sum: TokenBlacklistSumAggregateOutputType | null
  _min: TokenBlacklistMinAggregateOutputType | null
  _max: TokenBlacklistMaxAggregateOutputType | null
}

type GetTokenBlacklistGroupByPayload<T extends TokenBlacklistGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TokenBlacklistGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TokenBlacklistGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TokenBlacklistGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TokenBlacklistGroupByOutputType[P]>
      }
    >
  >



export type TokenBlacklistWhereInput = {
  AND?: Prisma.TokenBlacklistWhereInput | Prisma.TokenBlacklistWhereInput[]
  OR?: Prisma.TokenBlacklistWhereInput[]
  NOT?: Prisma.TokenBlacklistWhereInput | Prisma.TokenBlacklistWhereInput[]
  id?: Prisma.IntFilter<"TokenBlacklist"> | number
  token?: Prisma.StringFilter<"TokenBlacklist"> | string
  createdAt?: Prisma.DateTimeFilter<"TokenBlacklist"> | Date | string
  expiresAt?: Prisma.DateTimeFilter<"TokenBlacklist"> | Date | string
}

export type TokenBlacklistOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type TokenBlacklistWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  token?: string
  AND?: Prisma.TokenBlacklistWhereInput | Prisma.TokenBlacklistWhereInput[]
  OR?: Prisma.TokenBlacklistWhereInput[]
  NOT?: Prisma.TokenBlacklistWhereInput | Prisma.TokenBlacklistWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"TokenBlacklist"> | Date | string
  expiresAt?: Prisma.DateTimeFilter<"TokenBlacklist"> | Date | string
}, "id" | "token">

export type TokenBlacklistOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  _count?: Prisma.TokenBlacklistCountOrderByAggregateInput
  _avg?: Prisma.TokenBlacklistAvgOrderByAggregateInput
  _max?: Prisma.TokenBlacklistMaxOrderByAggregateInput
  _min?: Prisma.TokenBlacklistMinOrderByAggregateInput
  _sum?: Prisma.TokenBlacklistSumOrderByAggregateInput
}

export type TokenBlacklistScalarWhereWithAggregatesInput = {
  AND?: Prisma.TokenBlacklistScalarWhereWithAggregatesInput | Prisma.TokenBlacklistScalarWhereWithAggregatesInput[]
  OR?: Prisma.TokenBlacklistScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TokenBlacklistScalarWhereWithAggregatesInput | Prisma.TokenBlacklistScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"TokenBlacklist"> | number
  token?: Prisma.StringWithAggregatesFilter<"TokenBlacklist"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TokenBlacklist"> | Date | string
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"TokenBlacklist"> | Date | string
}

export type TokenBlacklistCreateInput = {
  token: string
  createdAt?: Date | string
  expiresAt: Date | string
}

export type TokenBlacklistUncheckedCreateInput = {
  id?: number
  token: string
  createdAt?: Date | string
  expiresAt: Date | string
}

export type TokenBlacklistUpdateInput = {
  token?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TokenBlacklistUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  token?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TokenBlacklistCreateManyInput = {
  id?: number
  token: string
  createdAt?: Date | string
  expiresAt: Date | string
}

export type TokenBlacklistUpdateManyMutationInput = {
  token?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TokenBlacklistUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  token?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TokenBlacklistCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type TokenBlacklistAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type TokenBlacklistMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type TokenBlacklistMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type TokenBlacklistSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type TokenBlacklistSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  token?: boolean
  createdAt?: boolean
  expiresAt?: boolean
}, ExtArgs["result"]["tokenBlacklist"]>

export type TokenBlacklistSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  token?: boolean
  createdAt?: boolean
  expiresAt?: boolean
}, ExtArgs["result"]["tokenBlacklist"]>

export type TokenBlacklistSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  token?: boolean
  createdAt?: boolean
  expiresAt?: boolean
}, ExtArgs["result"]["tokenBlacklist"]>

export type TokenBlacklistSelectScalar = {
  id?: boolean
  token?: boolean
  createdAt?: boolean
  expiresAt?: boolean
}

export type TokenBlacklistOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "token" | "createdAt" | "expiresAt", ExtArgs["result"]["tokenBlacklist"]>

export type $TokenBlacklistPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TokenBlacklist"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    token: string
    createdAt: Date
    expiresAt: Date
  }, ExtArgs["result"]["tokenBlacklist"]>
  composites: {}
}

export type TokenBlacklistGetPayload<S extends boolean | null | undefined | TokenBlacklistDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TokenBlacklistPayload, S>

export type TokenBlacklistCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TokenBlacklistFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: TokenBlacklistCountAggregateInputType | true
  }

export interface TokenBlacklistDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TokenBlacklist'], meta: { name: 'TokenBlacklist' } }
  /**
   * Find zero or one TokenBlacklist that matches the filter.
   * @param {TokenBlacklistFindUniqueArgs} args - Arguments to find a TokenBlacklist
   * @example
   * // Get one TokenBlacklist
   * const tokenBlacklist = await prisma.tokenBlacklist.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TokenBlacklistFindUniqueArgs>(args: Prisma.SelectSubset<T, TokenBlacklistFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TokenBlacklistClient<runtime.Types.Result.GetResult<Prisma.$TokenBlacklistPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TokenBlacklist that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TokenBlacklistFindUniqueOrThrowArgs} args - Arguments to find a TokenBlacklist
   * @example
   * // Get one TokenBlacklist
   * const tokenBlacklist = await prisma.tokenBlacklist.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TokenBlacklistFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TokenBlacklistFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TokenBlacklistClient<runtime.Types.Result.GetResult<Prisma.$TokenBlacklistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TokenBlacklist that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenBlacklistFindFirstArgs} args - Arguments to find a TokenBlacklist
   * @example
   * // Get one TokenBlacklist
   * const tokenBlacklist = await prisma.tokenBlacklist.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TokenBlacklistFindFirstArgs>(args?: Prisma.SelectSubset<T, TokenBlacklistFindFirstArgs<ExtArgs>>): Prisma.Prisma__TokenBlacklistClient<runtime.Types.Result.GetResult<Prisma.$TokenBlacklistPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TokenBlacklist that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenBlacklistFindFirstOrThrowArgs} args - Arguments to find a TokenBlacklist
   * @example
   * // Get one TokenBlacklist
   * const tokenBlacklist = await prisma.tokenBlacklist.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TokenBlacklistFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TokenBlacklistFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TokenBlacklistClient<runtime.Types.Result.GetResult<Prisma.$TokenBlacklistPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TokenBlacklists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenBlacklistFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TokenBlacklists
   * const tokenBlacklists = await prisma.tokenBlacklist.findMany()
   * 
   * // Get first 10 TokenBlacklists
   * const tokenBlacklists = await prisma.tokenBlacklist.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tokenBlacklistWithIdOnly = await prisma.tokenBlacklist.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TokenBlacklistFindManyArgs>(args?: Prisma.SelectSubset<T, TokenBlacklistFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TokenBlacklistPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TokenBlacklist.
   * @param {TokenBlacklistCreateArgs} args - Arguments to create a TokenBlacklist.
   * @example
   * // Create one TokenBlacklist
   * const TokenBlacklist = await prisma.tokenBlacklist.create({
   *   data: {
   *     // ... data to create a TokenBlacklist
   *   }
   * })
   * 
   */
  create<T extends TokenBlacklistCreateArgs>(args: Prisma.SelectSubset<T, TokenBlacklistCreateArgs<ExtArgs>>): Prisma.Prisma__TokenBlacklistClient<runtime.Types.Result.GetResult<Prisma.$TokenBlacklistPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TokenBlacklists.
   * @param {TokenBlacklistCreateManyArgs} args - Arguments to create many TokenBlacklists.
   * @example
   * // Create many TokenBlacklists
   * const tokenBlacklist = await prisma.tokenBlacklist.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TokenBlacklistCreateManyArgs>(args?: Prisma.SelectSubset<T, TokenBlacklistCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TokenBlacklists and returns the data saved in the database.
   * @param {TokenBlacklistCreateManyAndReturnArgs} args - Arguments to create many TokenBlacklists.
   * @example
   * // Create many TokenBlacklists
   * const tokenBlacklist = await prisma.tokenBlacklist.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TokenBlacklists and only return the `id`
   * const tokenBlacklistWithIdOnly = await prisma.tokenBlacklist.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TokenBlacklistCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TokenBlacklistCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TokenBlacklistPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TokenBlacklist.
   * @param {TokenBlacklistDeleteArgs} args - Arguments to delete one TokenBlacklist.
   * @example
   * // Delete one TokenBlacklist
   * const TokenBlacklist = await prisma.tokenBlacklist.delete({
   *   where: {
   *     // ... filter to delete one TokenBlacklist
   *   }
   * })
   * 
   */
  delete<T extends TokenBlacklistDeleteArgs>(args: Prisma.SelectSubset<T, TokenBlacklistDeleteArgs<ExtArgs>>): Prisma.Prisma__TokenBlacklistClient<runtime.Types.Result.GetResult<Prisma.$TokenBlacklistPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TokenBlacklist.
   * @param {TokenBlacklistUpdateArgs} args - Arguments to update one TokenBlacklist.
   * @example
   * // Update one TokenBlacklist
   * const tokenBlacklist = await prisma.tokenBlacklist.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TokenBlacklistUpdateArgs>(args: Prisma.SelectSubset<T, TokenBlacklistUpdateArgs<ExtArgs>>): Prisma.Prisma__TokenBlacklistClient<runtime.Types.Result.GetResult<Prisma.$TokenBlacklistPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TokenBlacklists.
   * @param {TokenBlacklistDeleteManyArgs} args - Arguments to filter TokenBlacklists to delete.
   * @example
   * // Delete a few TokenBlacklists
   * const { count } = await prisma.tokenBlacklist.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TokenBlacklistDeleteManyArgs>(args?: Prisma.SelectSubset<T, TokenBlacklistDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TokenBlacklists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenBlacklistUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TokenBlacklists
   * const tokenBlacklist = await prisma.tokenBlacklist.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TokenBlacklistUpdateManyArgs>(args: Prisma.SelectSubset<T, TokenBlacklistUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TokenBlacklists and returns the data updated in the database.
   * @param {TokenBlacklistUpdateManyAndReturnArgs} args - Arguments to update many TokenBlacklists.
   * @example
   * // Update many TokenBlacklists
   * const tokenBlacklist = await prisma.tokenBlacklist.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TokenBlacklists and only return the `id`
   * const tokenBlacklistWithIdOnly = await prisma.tokenBlacklist.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TokenBlacklistUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TokenBlacklistUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TokenBlacklistPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TokenBlacklist.
   * @param {TokenBlacklistUpsertArgs} args - Arguments to update or create a TokenBlacklist.
   * @example
   * // Update or create a TokenBlacklist
   * const tokenBlacklist = await prisma.tokenBlacklist.upsert({
   *   create: {
   *     // ... data to create a TokenBlacklist
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TokenBlacklist we want to update
   *   }
   * })
   */
  upsert<T extends TokenBlacklistUpsertArgs>(args: Prisma.SelectSubset<T, TokenBlacklistUpsertArgs<ExtArgs>>): Prisma.Prisma__TokenBlacklistClient<runtime.Types.Result.GetResult<Prisma.$TokenBlacklistPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TokenBlacklists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenBlacklistCountArgs} args - Arguments to filter TokenBlacklists to count.
   * @example
   * // Count the number of TokenBlacklists
   * const count = await prisma.tokenBlacklist.count({
   *   where: {
   *     // ... the filter for the TokenBlacklists we want to count
   *   }
   * })
  **/
  count<T extends TokenBlacklistCountArgs>(
    args?: Prisma.Subset<T, TokenBlacklistCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TokenBlacklistCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TokenBlacklist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenBlacklistAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TokenBlacklistAggregateArgs>(args: Prisma.Subset<T, TokenBlacklistAggregateArgs>): Prisma.PrismaPromise<GetTokenBlacklistAggregateType<T>>

  /**
   * Group by TokenBlacklist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenBlacklistGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TokenBlacklistGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TokenBlacklistGroupByArgs['orderBy'] }
      : { orderBy?: TokenBlacklistGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TokenBlacklistGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTokenBlacklistGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TokenBlacklist model
 */
readonly fields: TokenBlacklistFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TokenBlacklist.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TokenBlacklistClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TokenBlacklist model
 */
export interface TokenBlacklistFieldRefs {
  readonly id: Prisma.FieldRef<"TokenBlacklist", 'Int'>
  readonly token: Prisma.FieldRef<"TokenBlacklist", 'String'>
  readonly createdAt: Prisma.FieldRef<"TokenBlacklist", 'DateTime'>
  readonly expiresAt: Prisma.FieldRef<"TokenBlacklist", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TokenBlacklist findUnique
 */
export type TokenBlacklistFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenBlacklist
   */
  select?: Prisma.TokenBlacklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenBlacklist
   */
  omit?: Prisma.TokenBlacklistOmit<ExtArgs> | null
  /**
   * Filter, which TokenBlacklist to fetch.
   */
  where: Prisma.TokenBlacklistWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TokenBlacklist findUniqueOrThrow
 */
export type TokenBlacklistFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenBlacklist
   */
  select?: Prisma.TokenBlacklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenBlacklist
   */
  omit?: Prisma.TokenBlacklistOmit<ExtArgs> | null
  /**
   * Filter, which TokenBlacklist to fetch.
   */
  where: Prisma.TokenBlacklistWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TokenBlacklist findFirst
 */
export type TokenBlacklistFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenBlacklist
   */
  select?: Prisma.TokenBlacklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenBlacklist
   */
  omit?: Prisma.TokenBlacklistOmit<ExtArgs> | null
  /**
   * Filter, which TokenBlacklist to fetch.
   */
  where?: Prisma.TokenBlacklistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TokenBlacklists to fetch.
   */
  orderBy?: Prisma.TokenBlacklistOrderByWithRelationInput | Prisma.TokenBlacklistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TokenBlacklists.
   */
  cursor?: Prisma.TokenBlacklistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TokenBlacklists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TokenBlacklists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TokenBlacklists.
   */
  distinct?: Prisma.TokenBlacklistScalarFieldEnum | Prisma.TokenBlacklistScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TokenBlacklist findFirstOrThrow
 */
export type TokenBlacklistFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenBlacklist
   */
  select?: Prisma.TokenBlacklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenBlacklist
   */
  omit?: Prisma.TokenBlacklistOmit<ExtArgs> | null
  /**
   * Filter, which TokenBlacklist to fetch.
   */
  where?: Prisma.TokenBlacklistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TokenBlacklists to fetch.
   */
  orderBy?: Prisma.TokenBlacklistOrderByWithRelationInput | Prisma.TokenBlacklistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TokenBlacklists.
   */
  cursor?: Prisma.TokenBlacklistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TokenBlacklists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TokenBlacklists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TokenBlacklists.
   */
  distinct?: Prisma.TokenBlacklistScalarFieldEnum | Prisma.TokenBlacklistScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TokenBlacklist findMany
 */
export type TokenBlacklistFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenBlacklist
   */
  select?: Prisma.TokenBlacklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenBlacklist
   */
  omit?: Prisma.TokenBlacklistOmit<ExtArgs> | null
  /**
   * Filter, which TokenBlacklists to fetch.
   */
  where?: Prisma.TokenBlacklistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TokenBlacklists to fetch.
   */
  orderBy?: Prisma.TokenBlacklistOrderByWithRelationInput | Prisma.TokenBlacklistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TokenBlacklists.
   */
  cursor?: Prisma.TokenBlacklistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TokenBlacklists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TokenBlacklists.
   */
  skip?: number
  distinct?: Prisma.TokenBlacklistScalarFieldEnum | Prisma.TokenBlacklistScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TokenBlacklist create
 */
export type TokenBlacklistCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenBlacklist
   */
  select?: Prisma.TokenBlacklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenBlacklist
   */
  omit?: Prisma.TokenBlacklistOmit<ExtArgs> | null
  /**
   * The data needed to create a TokenBlacklist.
   */
  data: Prisma.XOR<Prisma.TokenBlacklistCreateInput, Prisma.TokenBlacklistUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TokenBlacklist createMany
 */
export type TokenBlacklistCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TokenBlacklists.
   */
  data: Prisma.TokenBlacklistCreateManyInput | Prisma.TokenBlacklistCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TokenBlacklist createManyAndReturn
 */
export type TokenBlacklistCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenBlacklist
   */
  select?: Prisma.TokenBlacklistSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TokenBlacklist
   */
  omit?: Prisma.TokenBlacklistOmit<ExtArgs> | null
  /**
   * The data used to create many TokenBlacklists.
   */
  data: Prisma.TokenBlacklistCreateManyInput | Prisma.TokenBlacklistCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TokenBlacklist update
 */
export type TokenBlacklistUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenBlacklist
   */
  select?: Prisma.TokenBlacklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenBlacklist
   */
  omit?: Prisma.TokenBlacklistOmit<ExtArgs> | null
  /**
   * The data needed to update a TokenBlacklist.
   */
  data: Prisma.XOR<Prisma.TokenBlacklistUpdateInput, Prisma.TokenBlacklistUncheckedUpdateInput>
  /**
   * Choose, which TokenBlacklist to update.
   */
  where: Prisma.TokenBlacklistWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TokenBlacklist updateMany
 */
export type TokenBlacklistUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TokenBlacklists.
   */
  data: Prisma.XOR<Prisma.TokenBlacklistUpdateManyMutationInput, Prisma.TokenBlacklistUncheckedUpdateManyInput>
  /**
   * Filter which TokenBlacklists to update
   */
  where?: Prisma.TokenBlacklistWhereInput
  /**
   * Limit how many TokenBlacklists to update.
   */
  limit?: number
}

/**
 * TokenBlacklist updateManyAndReturn
 */
export type TokenBlacklistUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenBlacklist
   */
  select?: Prisma.TokenBlacklistSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TokenBlacklist
   */
  omit?: Prisma.TokenBlacklistOmit<ExtArgs> | null
  /**
   * The data used to update TokenBlacklists.
   */
  data: Prisma.XOR<Prisma.TokenBlacklistUpdateManyMutationInput, Prisma.TokenBlacklistUncheckedUpdateManyInput>
  /**
   * Filter which TokenBlacklists to update
   */
  where?: Prisma.TokenBlacklistWhereInput
  /**
   * Limit how many TokenBlacklists to update.
   */
  limit?: number
}

/**
 * TokenBlacklist upsert
 */
export type TokenBlacklistUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenBlacklist
   */
  select?: Prisma.TokenBlacklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenBlacklist
   */
  omit?: Prisma.TokenBlacklistOmit<ExtArgs> | null
  /**
   * The filter to search for the TokenBlacklist to update in case it exists.
   */
  where: Prisma.TokenBlacklistWhereUniqueInput
  /**
   * In case the TokenBlacklist found by the `where` argument doesn't exist, create a new TokenBlacklist with this data.
   */
  create: Prisma.XOR<Prisma.TokenBlacklistCreateInput, Prisma.TokenBlacklistUncheckedCreateInput>
  /**
   * In case the TokenBlacklist was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TokenBlacklistUpdateInput, Prisma.TokenBlacklistUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TokenBlacklist delete
 */
export type TokenBlacklistDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenBlacklist
   */
  select?: Prisma.TokenBlacklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenBlacklist
   */
  omit?: Prisma.TokenBlacklistOmit<ExtArgs> | null
  /**
   * Filter which TokenBlacklist to delete.
   */
  where: Prisma.TokenBlacklistWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TokenBlacklist deleteMany
 */
export type TokenBlacklistDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TokenBlacklists to delete
   */
  where?: Prisma.TokenBlacklistWhereInput
  /**
   * Limit how many TokenBlacklists to delete.
   */
  limit?: number
}

/**
 * TokenBlacklist without action
 */
export type TokenBlacklistDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenBlacklist
   */
  select?: Prisma.TokenBlacklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenBlacklist
   */
  omit?: Prisma.TokenBlacklistOmit<ExtArgs> | null
}
