
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TwoFactorRecoveryCode` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TwoFactorRecoveryCode
 * 
 */
export type TwoFactorRecoveryCodeModel = runtime.Types.Result.DefaultSelection<Prisma.$TwoFactorRecoveryCodePayload>

export type AggregateTwoFactorRecoveryCode = {
  _count: TwoFactorRecoveryCodeCountAggregateOutputType | null
  _min: TwoFactorRecoveryCodeMinAggregateOutputType | null
  _max: TwoFactorRecoveryCodeMaxAggregateOutputType | null
}

export type TwoFactorRecoveryCodeMinAggregateOutputType = {
  id: string | null
  userId: string | null
  code: string | null
  isUsed: boolean | null
  usedAt: Date | null
  createdAt: Date | null
}

export type TwoFactorRecoveryCodeMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  code: string | null
  isUsed: boolean | null
  usedAt: Date | null
  createdAt: Date | null
}

export type TwoFactorRecoveryCodeCountAggregateOutputType = {
  id: number
  userId: number
  code: number
  isUsed: number
  usedAt: number
  createdAt: number
  _all: number
}


export type TwoFactorRecoveryCodeMinAggregateInputType = {
  id?: true
  userId?: true
  code?: true
  isUsed?: true
  usedAt?: true
  createdAt?: true
}

export type TwoFactorRecoveryCodeMaxAggregateInputType = {
  id?: true
  userId?: true
  code?: true
  isUsed?: true
  usedAt?: true
  createdAt?: true
}

export type TwoFactorRecoveryCodeCountAggregateInputType = {
  id?: true
  userId?: true
  code?: true
  isUsed?: true
  usedAt?: true
  createdAt?: true
  _all?: true
}

export type TwoFactorRecoveryCodeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TwoFactorRecoveryCode to aggregate.
   */
  where?: Prisma.TwoFactorRecoveryCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TwoFactorRecoveryCodes to fetch.
   */
  orderBy?: Prisma.TwoFactorRecoveryCodeOrderByWithRelationInput | Prisma.TwoFactorRecoveryCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TwoFactorRecoveryCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TwoFactorRecoveryCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TwoFactorRecoveryCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TwoFactorRecoveryCodes
  **/
  _count?: true | TwoFactorRecoveryCodeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TwoFactorRecoveryCodeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TwoFactorRecoveryCodeMaxAggregateInputType
}

export type GetTwoFactorRecoveryCodeAggregateType<T extends TwoFactorRecoveryCodeAggregateArgs> = {
      [P in keyof T & keyof AggregateTwoFactorRecoveryCode]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTwoFactorRecoveryCode[P]>
    : Prisma.GetScalarType<T[P], AggregateTwoFactorRecoveryCode[P]>
}




export type TwoFactorRecoveryCodeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TwoFactorRecoveryCodeWhereInput
  orderBy?: Prisma.TwoFactorRecoveryCodeOrderByWithAggregationInput | Prisma.TwoFactorRecoveryCodeOrderByWithAggregationInput[]
  by: Prisma.TwoFactorRecoveryCodeScalarFieldEnum[] | Prisma.TwoFactorRecoveryCodeScalarFieldEnum
  having?: Prisma.TwoFactorRecoveryCodeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TwoFactorRecoveryCodeCountAggregateInputType | true
  _min?: TwoFactorRecoveryCodeMinAggregateInputType
  _max?: TwoFactorRecoveryCodeMaxAggregateInputType
}

export type TwoFactorRecoveryCodeGroupByOutputType = {
  id: string
  userId: string
  code: string
  isUsed: boolean
  usedAt: Date | null
  createdAt: Date
  _count: TwoFactorRecoveryCodeCountAggregateOutputType | null
  _min: TwoFactorRecoveryCodeMinAggregateOutputType | null
  _max: TwoFactorRecoveryCodeMaxAggregateOutputType | null
}

type GetTwoFactorRecoveryCodeGroupByPayload<T extends TwoFactorRecoveryCodeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TwoFactorRecoveryCodeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TwoFactorRecoveryCodeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TwoFactorRecoveryCodeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TwoFactorRecoveryCodeGroupByOutputType[P]>
      }
    >
  >



export type TwoFactorRecoveryCodeWhereInput = {
  AND?: Prisma.TwoFactorRecoveryCodeWhereInput | Prisma.TwoFactorRecoveryCodeWhereInput[]
  OR?: Prisma.TwoFactorRecoveryCodeWhereInput[]
  NOT?: Prisma.TwoFactorRecoveryCodeWhereInput | Prisma.TwoFactorRecoveryCodeWhereInput[]
  id?: Prisma.StringFilter<"TwoFactorRecoveryCode"> | string
  userId?: Prisma.StringFilter<"TwoFactorRecoveryCode"> | string
  code?: Prisma.StringFilter<"TwoFactorRecoveryCode"> | string
  isUsed?: Prisma.BoolFilter<"TwoFactorRecoveryCode"> | boolean
  usedAt?: Prisma.DateTimeNullableFilter<"TwoFactorRecoveryCode"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"TwoFactorRecoveryCode"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type TwoFactorRecoveryCodeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  isUsed?: Prisma.SortOrder
  usedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type TwoFactorRecoveryCodeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TwoFactorRecoveryCodeWhereInput | Prisma.TwoFactorRecoveryCodeWhereInput[]
  OR?: Prisma.TwoFactorRecoveryCodeWhereInput[]
  NOT?: Prisma.TwoFactorRecoveryCodeWhereInput | Prisma.TwoFactorRecoveryCodeWhereInput[]
  userId?: Prisma.StringFilter<"TwoFactorRecoveryCode"> | string
  code?: Prisma.StringFilter<"TwoFactorRecoveryCode"> | string
  isUsed?: Prisma.BoolFilter<"TwoFactorRecoveryCode"> | boolean
  usedAt?: Prisma.DateTimeNullableFilter<"TwoFactorRecoveryCode"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"TwoFactorRecoveryCode"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type TwoFactorRecoveryCodeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  isUsed?: Prisma.SortOrder
  usedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.TwoFactorRecoveryCodeCountOrderByAggregateInput
  _max?: Prisma.TwoFactorRecoveryCodeMaxOrderByAggregateInput
  _min?: Prisma.TwoFactorRecoveryCodeMinOrderByAggregateInput
}

export type TwoFactorRecoveryCodeScalarWhereWithAggregatesInput = {
  AND?: Prisma.TwoFactorRecoveryCodeScalarWhereWithAggregatesInput | Prisma.TwoFactorRecoveryCodeScalarWhereWithAggregatesInput[]
  OR?: Prisma.TwoFactorRecoveryCodeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TwoFactorRecoveryCodeScalarWhereWithAggregatesInput | Prisma.TwoFactorRecoveryCodeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TwoFactorRecoveryCode"> | string
  userId?: Prisma.StringWithAggregatesFilter<"TwoFactorRecoveryCode"> | string
  code?: Prisma.StringWithAggregatesFilter<"TwoFactorRecoveryCode"> | string
  isUsed?: Prisma.BoolWithAggregatesFilter<"TwoFactorRecoveryCode"> | boolean
  usedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TwoFactorRecoveryCode"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TwoFactorRecoveryCode"> | Date | string
}

export type TwoFactorRecoveryCodeCreateInput = {
  id?: string
  code: string
  isUsed?: boolean
  usedAt?: Date | string | null
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTwoFactorRecoveryCodesInput
}

export type TwoFactorRecoveryCodeUncheckedCreateInput = {
  id?: string
  userId: string
  code: string
  isUsed?: boolean
  usedAt?: Date | string | null
  createdAt?: Date | string
}

export type TwoFactorRecoveryCodeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  isUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTwoFactorRecoveryCodesNestedInput
}

export type TwoFactorRecoveryCodeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  isUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TwoFactorRecoveryCodeCreateManyInput = {
  id?: string
  userId: string
  code: string
  isUsed?: boolean
  usedAt?: Date | string | null
  createdAt?: Date | string
}

export type TwoFactorRecoveryCodeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  isUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TwoFactorRecoveryCodeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  isUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TwoFactorRecoveryCodeListRelationFilter = {
  every?: Prisma.TwoFactorRecoveryCodeWhereInput
  some?: Prisma.TwoFactorRecoveryCodeWhereInput
  none?: Prisma.TwoFactorRecoveryCodeWhereInput
}

export type TwoFactorRecoveryCodeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TwoFactorRecoveryCodeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  isUsed?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TwoFactorRecoveryCodeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  isUsed?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TwoFactorRecoveryCodeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  isUsed?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TwoFactorRecoveryCodeCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TwoFactorRecoveryCodeCreateWithoutUserInput, Prisma.TwoFactorRecoveryCodeUncheckedCreateWithoutUserInput> | Prisma.TwoFactorRecoveryCodeCreateWithoutUserInput[] | Prisma.TwoFactorRecoveryCodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TwoFactorRecoveryCodeCreateOrConnectWithoutUserInput | Prisma.TwoFactorRecoveryCodeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TwoFactorRecoveryCodeCreateManyUserInputEnvelope
  connect?: Prisma.TwoFactorRecoveryCodeWhereUniqueInput | Prisma.TwoFactorRecoveryCodeWhereUniqueInput[]
}

export type TwoFactorRecoveryCodeUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TwoFactorRecoveryCodeCreateWithoutUserInput, Prisma.TwoFactorRecoveryCodeUncheckedCreateWithoutUserInput> | Prisma.TwoFactorRecoveryCodeCreateWithoutUserInput[] | Prisma.TwoFactorRecoveryCodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TwoFactorRecoveryCodeCreateOrConnectWithoutUserInput | Prisma.TwoFactorRecoveryCodeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TwoFactorRecoveryCodeCreateManyUserInputEnvelope
  connect?: Prisma.TwoFactorRecoveryCodeWhereUniqueInput | Prisma.TwoFactorRecoveryCodeWhereUniqueInput[]
}

export type TwoFactorRecoveryCodeUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TwoFactorRecoveryCodeCreateWithoutUserInput, Prisma.TwoFactorRecoveryCodeUncheckedCreateWithoutUserInput> | Prisma.TwoFactorRecoveryCodeCreateWithoutUserInput[] | Prisma.TwoFactorRecoveryCodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TwoFactorRecoveryCodeCreateOrConnectWithoutUserInput | Prisma.TwoFactorRecoveryCodeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TwoFactorRecoveryCodeUpsertWithWhereUniqueWithoutUserInput | Prisma.TwoFactorRecoveryCodeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TwoFactorRecoveryCodeCreateManyUserInputEnvelope
  set?: Prisma.TwoFactorRecoveryCodeWhereUniqueInput | Prisma.TwoFactorRecoveryCodeWhereUniqueInput[]
  disconnect?: Prisma.TwoFactorRecoveryCodeWhereUniqueInput | Prisma.TwoFactorRecoveryCodeWhereUniqueInput[]
  delete?: Prisma.TwoFactorRecoveryCodeWhereUniqueInput | Prisma.TwoFactorRecoveryCodeWhereUniqueInput[]
  connect?: Prisma.TwoFactorRecoveryCodeWhereUniqueInput | Prisma.TwoFactorRecoveryCodeWhereUniqueInput[]
  update?: Prisma.TwoFactorRecoveryCodeUpdateWithWhereUniqueWithoutUserInput | Prisma.TwoFactorRecoveryCodeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TwoFactorRecoveryCodeUpdateManyWithWhereWithoutUserInput | Prisma.TwoFactorRecoveryCodeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TwoFactorRecoveryCodeScalarWhereInput | Prisma.TwoFactorRecoveryCodeScalarWhereInput[]
}

export type TwoFactorRecoveryCodeUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TwoFactorRecoveryCodeCreateWithoutUserInput, Prisma.TwoFactorRecoveryCodeUncheckedCreateWithoutUserInput> | Prisma.TwoFactorRecoveryCodeCreateWithoutUserInput[] | Prisma.TwoFactorRecoveryCodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TwoFactorRecoveryCodeCreateOrConnectWithoutUserInput | Prisma.TwoFactorRecoveryCodeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TwoFactorRecoveryCodeUpsertWithWhereUniqueWithoutUserInput | Prisma.TwoFactorRecoveryCodeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TwoFactorRecoveryCodeCreateManyUserInputEnvelope
  set?: Prisma.TwoFactorRecoveryCodeWhereUniqueInput | Prisma.TwoFactorRecoveryCodeWhereUniqueInput[]
  disconnect?: Prisma.TwoFactorRecoveryCodeWhereUniqueInput | Prisma.TwoFactorRecoveryCodeWhereUniqueInput[]
  delete?: Prisma.TwoFactorRecoveryCodeWhereUniqueInput | Prisma.TwoFactorRecoveryCodeWhereUniqueInput[]
  connect?: Prisma.TwoFactorRecoveryCodeWhereUniqueInput | Prisma.TwoFactorRecoveryCodeWhereUniqueInput[]
  update?: Prisma.TwoFactorRecoveryCodeUpdateWithWhereUniqueWithoutUserInput | Prisma.TwoFactorRecoveryCodeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TwoFactorRecoveryCodeUpdateManyWithWhereWithoutUserInput | Prisma.TwoFactorRecoveryCodeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TwoFactorRecoveryCodeScalarWhereInput | Prisma.TwoFactorRecoveryCodeScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type TwoFactorRecoveryCodeCreateWithoutUserInput = {
  id?: string
  code: string
  isUsed?: boolean
  usedAt?: Date | string | null
  createdAt?: Date | string
}

export type TwoFactorRecoveryCodeUncheckedCreateWithoutUserInput = {
  id?: string
  code: string
  isUsed?: boolean
  usedAt?: Date | string | null
  createdAt?: Date | string
}

export type TwoFactorRecoveryCodeCreateOrConnectWithoutUserInput = {
  where: Prisma.TwoFactorRecoveryCodeWhereUniqueInput
  create: Prisma.XOR<Prisma.TwoFactorRecoveryCodeCreateWithoutUserInput, Prisma.TwoFactorRecoveryCodeUncheckedCreateWithoutUserInput>
}

export type TwoFactorRecoveryCodeCreateManyUserInputEnvelope = {
  data: Prisma.TwoFactorRecoveryCodeCreateManyUserInput | Prisma.TwoFactorRecoveryCodeCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type TwoFactorRecoveryCodeUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.TwoFactorRecoveryCodeWhereUniqueInput
  update: Prisma.XOR<Prisma.TwoFactorRecoveryCodeUpdateWithoutUserInput, Prisma.TwoFactorRecoveryCodeUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.TwoFactorRecoveryCodeCreateWithoutUserInput, Prisma.TwoFactorRecoveryCodeUncheckedCreateWithoutUserInput>
}

export type TwoFactorRecoveryCodeUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.TwoFactorRecoveryCodeWhereUniqueInput
  data: Prisma.XOR<Prisma.TwoFactorRecoveryCodeUpdateWithoutUserInput, Prisma.TwoFactorRecoveryCodeUncheckedUpdateWithoutUserInput>
}

export type TwoFactorRecoveryCodeUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.TwoFactorRecoveryCodeScalarWhereInput
  data: Prisma.XOR<Prisma.TwoFactorRecoveryCodeUpdateManyMutationInput, Prisma.TwoFactorRecoveryCodeUncheckedUpdateManyWithoutUserInput>
}

export type TwoFactorRecoveryCodeScalarWhereInput = {
  AND?: Prisma.TwoFactorRecoveryCodeScalarWhereInput | Prisma.TwoFactorRecoveryCodeScalarWhereInput[]
  OR?: Prisma.TwoFactorRecoveryCodeScalarWhereInput[]
  NOT?: Prisma.TwoFactorRecoveryCodeScalarWhereInput | Prisma.TwoFactorRecoveryCodeScalarWhereInput[]
  id?: Prisma.StringFilter<"TwoFactorRecoveryCode"> | string
  userId?: Prisma.StringFilter<"TwoFactorRecoveryCode"> | string
  code?: Prisma.StringFilter<"TwoFactorRecoveryCode"> | string
  isUsed?: Prisma.BoolFilter<"TwoFactorRecoveryCode"> | boolean
  usedAt?: Prisma.DateTimeNullableFilter<"TwoFactorRecoveryCode"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"TwoFactorRecoveryCode"> | Date | string
}

export type TwoFactorRecoveryCodeCreateManyUserInput = {
  id?: string
  code: string
  isUsed?: boolean
  usedAt?: Date | string | null
  createdAt?: Date | string
}

export type TwoFactorRecoveryCodeUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  isUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TwoFactorRecoveryCodeUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  isUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TwoFactorRecoveryCodeUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  isUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TwoFactorRecoveryCodeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  code?: boolean
  isUsed?: boolean
  usedAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["twoFactorRecoveryCode"]>

export type TwoFactorRecoveryCodeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  code?: boolean
  isUsed?: boolean
  usedAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["twoFactorRecoveryCode"]>

export type TwoFactorRecoveryCodeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  code?: boolean
  isUsed?: boolean
  usedAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["twoFactorRecoveryCode"]>

export type TwoFactorRecoveryCodeSelectScalar = {
  id?: boolean
  userId?: boolean
  code?: boolean
  isUsed?: boolean
  usedAt?: boolean
  createdAt?: boolean
}

export type TwoFactorRecoveryCodeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "code" | "isUsed" | "usedAt" | "createdAt", ExtArgs["result"]["twoFactorRecoveryCode"]>
export type TwoFactorRecoveryCodeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type TwoFactorRecoveryCodeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type TwoFactorRecoveryCodeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $TwoFactorRecoveryCodePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TwoFactorRecoveryCode"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    code: string
    isUsed: boolean
    usedAt: Date | null
    createdAt: Date
  }, ExtArgs["result"]["twoFactorRecoveryCode"]>
  composites: {}
}

export type TwoFactorRecoveryCodeGetPayload<S extends boolean | null | undefined | TwoFactorRecoveryCodeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TwoFactorRecoveryCodePayload, S>

export type TwoFactorRecoveryCodeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TwoFactorRecoveryCodeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: TwoFactorRecoveryCodeCountAggregateInputType | true
  }

export interface TwoFactorRecoveryCodeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TwoFactorRecoveryCode'], meta: { name: 'TwoFactorRecoveryCode' } }
  /**
   * Find zero or one TwoFactorRecoveryCode that matches the filter.
   * @param {TwoFactorRecoveryCodeFindUniqueArgs} args - Arguments to find a TwoFactorRecoveryCode
   * @example
   * // Get one TwoFactorRecoveryCode
   * const twoFactorRecoveryCode = await prisma.twoFactorRecoveryCode.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TwoFactorRecoveryCodeFindUniqueArgs>(args: Prisma.SelectSubset<T, TwoFactorRecoveryCodeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TwoFactorRecoveryCodeClient<runtime.Types.Result.GetResult<Prisma.$TwoFactorRecoveryCodePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TwoFactorRecoveryCode that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TwoFactorRecoveryCodeFindUniqueOrThrowArgs} args - Arguments to find a TwoFactorRecoveryCode
   * @example
   * // Get one TwoFactorRecoveryCode
   * const twoFactorRecoveryCode = await prisma.twoFactorRecoveryCode.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TwoFactorRecoveryCodeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TwoFactorRecoveryCodeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TwoFactorRecoveryCodeClient<runtime.Types.Result.GetResult<Prisma.$TwoFactorRecoveryCodePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TwoFactorRecoveryCode that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TwoFactorRecoveryCodeFindFirstArgs} args - Arguments to find a TwoFactorRecoveryCode
   * @example
   * // Get one TwoFactorRecoveryCode
   * const twoFactorRecoveryCode = await prisma.twoFactorRecoveryCode.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TwoFactorRecoveryCodeFindFirstArgs>(args?: Prisma.SelectSubset<T, TwoFactorRecoveryCodeFindFirstArgs<ExtArgs>>): Prisma.Prisma__TwoFactorRecoveryCodeClient<runtime.Types.Result.GetResult<Prisma.$TwoFactorRecoveryCodePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TwoFactorRecoveryCode that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TwoFactorRecoveryCodeFindFirstOrThrowArgs} args - Arguments to find a TwoFactorRecoveryCode
   * @example
   * // Get one TwoFactorRecoveryCode
   * const twoFactorRecoveryCode = await prisma.twoFactorRecoveryCode.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TwoFactorRecoveryCodeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TwoFactorRecoveryCodeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TwoFactorRecoveryCodeClient<runtime.Types.Result.GetResult<Prisma.$TwoFactorRecoveryCodePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TwoFactorRecoveryCodes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TwoFactorRecoveryCodeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TwoFactorRecoveryCodes
   * const twoFactorRecoveryCodes = await prisma.twoFactorRecoveryCode.findMany()
   * 
   * // Get first 10 TwoFactorRecoveryCodes
   * const twoFactorRecoveryCodes = await prisma.twoFactorRecoveryCode.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const twoFactorRecoveryCodeWithIdOnly = await prisma.twoFactorRecoveryCode.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TwoFactorRecoveryCodeFindManyArgs>(args?: Prisma.SelectSubset<T, TwoFactorRecoveryCodeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TwoFactorRecoveryCodePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TwoFactorRecoveryCode.
   * @param {TwoFactorRecoveryCodeCreateArgs} args - Arguments to create a TwoFactorRecoveryCode.
   * @example
   * // Create one TwoFactorRecoveryCode
   * const TwoFactorRecoveryCode = await prisma.twoFactorRecoveryCode.create({
   *   data: {
   *     // ... data to create a TwoFactorRecoveryCode
   *   }
   * })
   * 
   */
  create<T extends TwoFactorRecoveryCodeCreateArgs>(args: Prisma.SelectSubset<T, TwoFactorRecoveryCodeCreateArgs<ExtArgs>>): Prisma.Prisma__TwoFactorRecoveryCodeClient<runtime.Types.Result.GetResult<Prisma.$TwoFactorRecoveryCodePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TwoFactorRecoveryCodes.
   * @param {TwoFactorRecoveryCodeCreateManyArgs} args - Arguments to create many TwoFactorRecoveryCodes.
   * @example
   * // Create many TwoFactorRecoveryCodes
   * const twoFactorRecoveryCode = await prisma.twoFactorRecoveryCode.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TwoFactorRecoveryCodeCreateManyArgs>(args?: Prisma.SelectSubset<T, TwoFactorRecoveryCodeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TwoFactorRecoveryCodes and returns the data saved in the database.
   * @param {TwoFactorRecoveryCodeCreateManyAndReturnArgs} args - Arguments to create many TwoFactorRecoveryCodes.
   * @example
   * // Create many TwoFactorRecoveryCodes
   * const twoFactorRecoveryCode = await prisma.twoFactorRecoveryCode.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TwoFactorRecoveryCodes and only return the `id`
   * const twoFactorRecoveryCodeWithIdOnly = await prisma.twoFactorRecoveryCode.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TwoFactorRecoveryCodeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TwoFactorRecoveryCodeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TwoFactorRecoveryCodePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TwoFactorRecoveryCode.
   * @param {TwoFactorRecoveryCodeDeleteArgs} args - Arguments to delete one TwoFactorRecoveryCode.
   * @example
   * // Delete one TwoFactorRecoveryCode
   * const TwoFactorRecoveryCode = await prisma.twoFactorRecoveryCode.delete({
   *   where: {
   *     // ... filter to delete one TwoFactorRecoveryCode
   *   }
   * })
   * 
   */
  delete<T extends TwoFactorRecoveryCodeDeleteArgs>(args: Prisma.SelectSubset<T, TwoFactorRecoveryCodeDeleteArgs<ExtArgs>>): Prisma.Prisma__TwoFactorRecoveryCodeClient<runtime.Types.Result.GetResult<Prisma.$TwoFactorRecoveryCodePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TwoFactorRecoveryCode.
   * @param {TwoFactorRecoveryCodeUpdateArgs} args - Arguments to update one TwoFactorRecoveryCode.
   * @example
   * // Update one TwoFactorRecoveryCode
   * const twoFactorRecoveryCode = await prisma.twoFactorRecoveryCode.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TwoFactorRecoveryCodeUpdateArgs>(args: Prisma.SelectSubset<T, TwoFactorRecoveryCodeUpdateArgs<ExtArgs>>): Prisma.Prisma__TwoFactorRecoveryCodeClient<runtime.Types.Result.GetResult<Prisma.$TwoFactorRecoveryCodePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TwoFactorRecoveryCodes.
   * @param {TwoFactorRecoveryCodeDeleteManyArgs} args - Arguments to filter TwoFactorRecoveryCodes to delete.
   * @example
   * // Delete a few TwoFactorRecoveryCodes
   * const { count } = await prisma.twoFactorRecoveryCode.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TwoFactorRecoveryCodeDeleteManyArgs>(args?: Prisma.SelectSubset<T, TwoFactorRecoveryCodeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TwoFactorRecoveryCodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TwoFactorRecoveryCodeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TwoFactorRecoveryCodes
   * const twoFactorRecoveryCode = await prisma.twoFactorRecoveryCode.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TwoFactorRecoveryCodeUpdateManyArgs>(args: Prisma.SelectSubset<T, TwoFactorRecoveryCodeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TwoFactorRecoveryCodes and returns the data updated in the database.
   * @param {TwoFactorRecoveryCodeUpdateManyAndReturnArgs} args - Arguments to update many TwoFactorRecoveryCodes.
   * @example
   * // Update many TwoFactorRecoveryCodes
   * const twoFactorRecoveryCode = await prisma.twoFactorRecoveryCode.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TwoFactorRecoveryCodes and only return the `id`
   * const twoFactorRecoveryCodeWithIdOnly = await prisma.twoFactorRecoveryCode.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TwoFactorRecoveryCodeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TwoFactorRecoveryCodeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TwoFactorRecoveryCodePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TwoFactorRecoveryCode.
   * @param {TwoFactorRecoveryCodeUpsertArgs} args - Arguments to update or create a TwoFactorRecoveryCode.
   * @example
   * // Update or create a TwoFactorRecoveryCode
   * const twoFactorRecoveryCode = await prisma.twoFactorRecoveryCode.upsert({
   *   create: {
   *     // ... data to create a TwoFactorRecoveryCode
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TwoFactorRecoveryCode we want to update
   *   }
   * })
   */
  upsert<T extends TwoFactorRecoveryCodeUpsertArgs>(args: Prisma.SelectSubset<T, TwoFactorRecoveryCodeUpsertArgs<ExtArgs>>): Prisma.Prisma__TwoFactorRecoveryCodeClient<runtime.Types.Result.GetResult<Prisma.$TwoFactorRecoveryCodePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TwoFactorRecoveryCodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TwoFactorRecoveryCodeCountArgs} args - Arguments to filter TwoFactorRecoveryCodes to count.
   * @example
   * // Count the number of TwoFactorRecoveryCodes
   * const count = await prisma.twoFactorRecoveryCode.count({
   *   where: {
   *     // ... the filter for the TwoFactorRecoveryCodes we want to count
   *   }
   * })
  **/
  count<T extends TwoFactorRecoveryCodeCountArgs>(
    args?: Prisma.Subset<T, TwoFactorRecoveryCodeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TwoFactorRecoveryCodeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TwoFactorRecoveryCode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TwoFactorRecoveryCodeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TwoFactorRecoveryCodeAggregateArgs>(args: Prisma.Subset<T, TwoFactorRecoveryCodeAggregateArgs>): Prisma.PrismaPromise<GetTwoFactorRecoveryCodeAggregateType<T>>

  /**
   * Group by TwoFactorRecoveryCode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TwoFactorRecoveryCodeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TwoFactorRecoveryCodeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TwoFactorRecoveryCodeGroupByArgs['orderBy'] }
      : { orderBy?: TwoFactorRecoveryCodeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TwoFactorRecoveryCodeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTwoFactorRecoveryCodeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TwoFactorRecoveryCode model
 */
readonly fields: TwoFactorRecoveryCodeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TwoFactorRecoveryCode.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TwoFactorRecoveryCodeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TwoFactorRecoveryCode model
 */
export interface TwoFactorRecoveryCodeFieldRefs {
  readonly id: Prisma.FieldRef<"TwoFactorRecoveryCode", 'String'>
  readonly userId: Prisma.FieldRef<"TwoFactorRecoveryCode", 'String'>
  readonly code: Prisma.FieldRef<"TwoFactorRecoveryCode", 'String'>
  readonly isUsed: Prisma.FieldRef<"TwoFactorRecoveryCode", 'Boolean'>
  readonly usedAt: Prisma.FieldRef<"TwoFactorRecoveryCode", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"TwoFactorRecoveryCode", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TwoFactorRecoveryCode findUnique
 */
export type TwoFactorRecoveryCodeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwoFactorRecoveryCode
   */
  select?: Prisma.TwoFactorRecoveryCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwoFactorRecoveryCode
   */
  omit?: Prisma.TwoFactorRecoveryCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwoFactorRecoveryCodeInclude<ExtArgs> | null
  /**
   * Filter, which TwoFactorRecoveryCode to fetch.
   */
  where: Prisma.TwoFactorRecoveryCodeWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TwoFactorRecoveryCode findUniqueOrThrow
 */
export type TwoFactorRecoveryCodeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwoFactorRecoveryCode
   */
  select?: Prisma.TwoFactorRecoveryCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwoFactorRecoveryCode
   */
  omit?: Prisma.TwoFactorRecoveryCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwoFactorRecoveryCodeInclude<ExtArgs> | null
  /**
   * Filter, which TwoFactorRecoveryCode to fetch.
   */
  where: Prisma.TwoFactorRecoveryCodeWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TwoFactorRecoveryCode findFirst
 */
export type TwoFactorRecoveryCodeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwoFactorRecoveryCode
   */
  select?: Prisma.TwoFactorRecoveryCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwoFactorRecoveryCode
   */
  omit?: Prisma.TwoFactorRecoveryCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwoFactorRecoveryCodeInclude<ExtArgs> | null
  /**
   * Filter, which TwoFactorRecoveryCode to fetch.
   */
  where?: Prisma.TwoFactorRecoveryCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TwoFactorRecoveryCodes to fetch.
   */
  orderBy?: Prisma.TwoFactorRecoveryCodeOrderByWithRelationInput | Prisma.TwoFactorRecoveryCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TwoFactorRecoveryCodes.
   */
  cursor?: Prisma.TwoFactorRecoveryCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TwoFactorRecoveryCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TwoFactorRecoveryCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TwoFactorRecoveryCodes.
   */
  distinct?: Prisma.TwoFactorRecoveryCodeScalarFieldEnum | Prisma.TwoFactorRecoveryCodeScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TwoFactorRecoveryCode findFirstOrThrow
 */
export type TwoFactorRecoveryCodeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwoFactorRecoveryCode
   */
  select?: Prisma.TwoFactorRecoveryCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwoFactorRecoveryCode
   */
  omit?: Prisma.TwoFactorRecoveryCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwoFactorRecoveryCodeInclude<ExtArgs> | null
  /**
   * Filter, which TwoFactorRecoveryCode to fetch.
   */
  where?: Prisma.TwoFactorRecoveryCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TwoFactorRecoveryCodes to fetch.
   */
  orderBy?: Prisma.TwoFactorRecoveryCodeOrderByWithRelationInput | Prisma.TwoFactorRecoveryCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TwoFactorRecoveryCodes.
   */
  cursor?: Prisma.TwoFactorRecoveryCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TwoFactorRecoveryCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TwoFactorRecoveryCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TwoFactorRecoveryCodes.
   */
  distinct?: Prisma.TwoFactorRecoveryCodeScalarFieldEnum | Prisma.TwoFactorRecoveryCodeScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TwoFactorRecoveryCode findMany
 */
export type TwoFactorRecoveryCodeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwoFactorRecoveryCode
   */
  select?: Prisma.TwoFactorRecoveryCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwoFactorRecoveryCode
   */
  omit?: Prisma.TwoFactorRecoveryCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwoFactorRecoveryCodeInclude<ExtArgs> | null
  /**
   * Filter, which TwoFactorRecoveryCodes to fetch.
   */
  where?: Prisma.TwoFactorRecoveryCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TwoFactorRecoveryCodes to fetch.
   */
  orderBy?: Prisma.TwoFactorRecoveryCodeOrderByWithRelationInput | Prisma.TwoFactorRecoveryCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TwoFactorRecoveryCodes.
   */
  cursor?: Prisma.TwoFactorRecoveryCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TwoFactorRecoveryCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TwoFactorRecoveryCodes.
   */
  skip?: number
  distinct?: Prisma.TwoFactorRecoveryCodeScalarFieldEnum | Prisma.TwoFactorRecoveryCodeScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TwoFactorRecoveryCode create
 */
export type TwoFactorRecoveryCodeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwoFactorRecoveryCode
   */
  select?: Prisma.TwoFactorRecoveryCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwoFactorRecoveryCode
   */
  omit?: Prisma.TwoFactorRecoveryCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwoFactorRecoveryCodeInclude<ExtArgs> | null
  /**
   * The data needed to create a TwoFactorRecoveryCode.
   */
  data: Prisma.XOR<Prisma.TwoFactorRecoveryCodeCreateInput, Prisma.TwoFactorRecoveryCodeUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TwoFactorRecoveryCode createMany
 */
export type TwoFactorRecoveryCodeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TwoFactorRecoveryCodes.
   */
  data: Prisma.TwoFactorRecoveryCodeCreateManyInput | Prisma.TwoFactorRecoveryCodeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TwoFactorRecoveryCode createManyAndReturn
 */
export type TwoFactorRecoveryCodeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwoFactorRecoveryCode
   */
  select?: Prisma.TwoFactorRecoveryCodeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TwoFactorRecoveryCode
   */
  omit?: Prisma.TwoFactorRecoveryCodeOmit<ExtArgs> | null
  /**
   * The data used to create many TwoFactorRecoveryCodes.
   */
  data: Prisma.TwoFactorRecoveryCodeCreateManyInput | Prisma.TwoFactorRecoveryCodeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwoFactorRecoveryCodeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TwoFactorRecoveryCode update
 */
export type TwoFactorRecoveryCodeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwoFactorRecoveryCode
   */
  select?: Prisma.TwoFactorRecoveryCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwoFactorRecoveryCode
   */
  omit?: Prisma.TwoFactorRecoveryCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwoFactorRecoveryCodeInclude<ExtArgs> | null
  /**
   * The data needed to update a TwoFactorRecoveryCode.
   */
  data: Prisma.XOR<Prisma.TwoFactorRecoveryCodeUpdateInput, Prisma.TwoFactorRecoveryCodeUncheckedUpdateInput>
  /**
   * Choose, which TwoFactorRecoveryCode to update.
   */
  where: Prisma.TwoFactorRecoveryCodeWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TwoFactorRecoveryCode updateMany
 */
export type TwoFactorRecoveryCodeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TwoFactorRecoveryCodes.
   */
  data: Prisma.XOR<Prisma.TwoFactorRecoveryCodeUpdateManyMutationInput, Prisma.TwoFactorRecoveryCodeUncheckedUpdateManyInput>
  /**
   * Filter which TwoFactorRecoveryCodes to update
   */
  where?: Prisma.TwoFactorRecoveryCodeWhereInput
  /**
   * Limit how many TwoFactorRecoveryCodes to update.
   */
  limit?: number
}

/**
 * TwoFactorRecoveryCode updateManyAndReturn
 */
export type TwoFactorRecoveryCodeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwoFactorRecoveryCode
   */
  select?: Prisma.TwoFactorRecoveryCodeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TwoFactorRecoveryCode
   */
  omit?: Prisma.TwoFactorRecoveryCodeOmit<ExtArgs> | null
  /**
   * The data used to update TwoFactorRecoveryCodes.
   */
  data: Prisma.XOR<Prisma.TwoFactorRecoveryCodeUpdateManyMutationInput, Prisma.TwoFactorRecoveryCodeUncheckedUpdateManyInput>
  /**
   * Filter which TwoFactorRecoveryCodes to update
   */
  where?: Prisma.TwoFactorRecoveryCodeWhereInput
  /**
   * Limit how many TwoFactorRecoveryCodes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwoFactorRecoveryCodeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TwoFactorRecoveryCode upsert
 */
export type TwoFactorRecoveryCodeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwoFactorRecoveryCode
   */
  select?: Prisma.TwoFactorRecoveryCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwoFactorRecoveryCode
   */
  omit?: Prisma.TwoFactorRecoveryCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwoFactorRecoveryCodeInclude<ExtArgs> | null
  /**
   * The filter to search for the TwoFactorRecoveryCode to update in case it exists.
   */
  where: Prisma.TwoFactorRecoveryCodeWhereUniqueInput
  /**
   * In case the TwoFactorRecoveryCode found by the `where` argument doesn't exist, create a new TwoFactorRecoveryCode with this data.
   */
  create: Prisma.XOR<Prisma.TwoFactorRecoveryCodeCreateInput, Prisma.TwoFactorRecoveryCodeUncheckedCreateInput>
  /**
   * In case the TwoFactorRecoveryCode was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TwoFactorRecoveryCodeUpdateInput, Prisma.TwoFactorRecoveryCodeUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TwoFactorRecoveryCode delete
 */
export type TwoFactorRecoveryCodeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwoFactorRecoveryCode
   */
  select?: Prisma.TwoFactorRecoveryCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwoFactorRecoveryCode
   */
  omit?: Prisma.TwoFactorRecoveryCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwoFactorRecoveryCodeInclude<ExtArgs> | null
  /**
   * Filter which TwoFactorRecoveryCode to delete.
   */
  where: Prisma.TwoFactorRecoveryCodeWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TwoFactorRecoveryCode deleteMany
 */
export type TwoFactorRecoveryCodeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TwoFactorRecoveryCodes to delete
   */
  where?: Prisma.TwoFactorRecoveryCodeWhereInput
  /**
   * Limit how many TwoFactorRecoveryCodes to delete.
   */
  limit?: number
}

/**
 * TwoFactorRecoveryCode without action
 */
export type TwoFactorRecoveryCodeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwoFactorRecoveryCode
   */
  select?: Prisma.TwoFactorRecoveryCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwoFactorRecoveryCode
   */
  omit?: Prisma.TwoFactorRecoveryCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwoFactorRecoveryCodeInclude<ExtArgs> | null
}
